<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="8" total="18" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="TestNgPOM Selenium Easy Test Suite" duration-ms="4534" started-at="2020-05-24T15:19:45Z" finished-at="2020-05-24T15:19:50Z">
    <groups>
    </groups>
    <test name="Selenium Easy Test Site Test Cases" duration-ms="4534" started-at="2020-05-24T15:19:45Z" finished-at="2020-05-24T15:19:50Z">
      <class name="com.qa.testcases.DatePickersPageTests">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.qa.testcases.DatePickersPageTests@2bbf180e]" name="setUpClass" is-config="true" duration-ms="2" started-at="2020-05-24T15:19:47Z" finished-at="2020-05-24T15:19:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="datePickersPageTitleTest()[pri:1, instance:com.qa.testcases.DatePickersPageTests@2bbf180e]" name="datePickersPageTitleTest" duration-ms="1381" started-at="2020-05-24T15:19:47Z" finished-at="2020-05-24T15:19:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- datePickersPageTitleTest -->
        <test-method status="PASS" signature="seleniumEasyLogoTest()[pri:2, instance:com.qa.testcases.DatePickersPageTests@2bbf180e]" name="seleniumEasyLogoTest" duration-ms="95" started-at="2020-05-24T15:19:50Z" finished-at="2020-05-24T15:19:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seleniumEasyLogoTest -->
      </class> <!-- com.qa.testcases.DatePickersPageTests -->
      <class name="com.qa.testcases.InputElementsPageTests">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.qa.testcases.InputElementsPageTests@d4342c2]" name="setUpClass" is-config="true" duration-ms="3" started-at="2020-05-24T15:19:46Z" finished-at="2020-05-24T15:19:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="navigateToinputElementsPageTest()[pri:1, instance:com.qa.testcases.InputElementsPageTests@d4342c2]" name="navigateToinputElementsPageTest" duration-ms="1008" started-at="2020-05-24T15:19:46Z" finished-at="2020-05-24T15:19:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToinputElementsPageTest -->
        <test-method status="FAIL" signature="inputElementsPageTitleTest()[pri:2, instance:com.qa.testcases.InputElementsPageTests@d4342c2]" name="inputElementsPageTitleTest" duration-ms="13" started-at="2020-05-24T15:19:49Z" finished-at="2020-05-24T15:19:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Selenium Easy - Best Demo website for Bootstrap Date picker] but found [Selenium Easy Demo - Simple Form to Automate using Selenium]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Selenium Easy - Best Demo website for Bootstrap Date picker] but found [Selenium Easy Demo - Simple Form to Automate using Selenium]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.testcases.InputElementsPageTests.inputElementsPageTitleTest(InputElementsPageTests.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inputElementsPageTitleTest -->
      </class> <!-- com.qa.testcases.InputElementsPageTests -->
      <class name="com.qa.testcases.HomePageTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.testcases.HomePageTests@4e91d63f]" name="setUp" is-config="true" duration-ms="6338" started-at="2020-05-24T15:19:39Z" finished-at="2020-05-24T15:19:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.qa.testcases.HomePageTests@4e91d63f]" name="setUpClass" is-config="true" duration-ms="27" started-at="2020-05-24T15:19:46Z" finished-at="2020-05-24T15:19:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="seleniumEasyLogoTest()[pri:1, instance:com.qa.testcases.HomePageTests@4e91d63f]" name="seleniumEasyLogoTest" duration-ms="116" started-at="2020-05-24T15:19:46Z" finished-at="2020-05-24T15:19:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seleniumEasyLogoTest -->
        <test-method status="FAIL" signature="homePageTitleTest()[pri:2, instance:com.qa.testcases.HomePageTests@4e91d63f]" name="homePageTitleTest" duration-ms="18" started-at="2020-05-24T15:19:49Z" finished-at="2020-05-24T15:19:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home Page title is not matched expected [Selenium Easy - Best Demo website for Bootstrap Date picker] but found [Selenium Easy - Best Demo website to practice Selenium Webdriver Online]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home Page title is not matched expected [Selenium Easy - Best Demo website for Bootstrap Date picker] but found [Selenium Easy - Best Demo website to practice Selenium Webdriver Online]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.qa.testcases.HomePageTests.homePageTitleTest(HomePageTests.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.HomePageTests@4e91d63f]" name="tearDown" is-config="true" duration-ms="916" started-at="2020-05-24T15:19:51Z" finished-at="2020-05-24T15:19:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.HomePageTests -->
      <class name="com.qa.testcases.DummyTestClass1">
        <test-method status="FAIL" signature="dummyOne_FailTest()[pri:1, instance:com.qa.testcases.DummyTestClass1@163e4e87]" name="dummyOne_FailTest" duration-ms="2" started-at="2020-05-24T15:19:48Z" finished-at="2020-05-24T15:19:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed
at org.testng.Assert.fail(Assert.java:96)
at com.qa.testcases.DummyTestClass1.dummyOne_FailTest(DummyTestClass1.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dummyOne_FailTest -->
        <test-method status="PASS" signature="dummyOne_PassTest()[pri:2, instance:com.qa.testcases.DummyTestClass1@163e4e87]" name="dummyOne_PassTest" duration-ms="19" started-at="2020-05-24T15:19:50Z" finished-at="2020-05-24T15:19:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dummyOne_PassTest -->
      </class> <!-- com.qa.testcases.DummyTestClass1 -->
      <class name="com.qa.testcases.DummyTestClass2">
        <test-method status="FAIL" signature="dummyTwo_FailTest()[pri:1, instance:com.qa.testcases.DummyTestClass2@56de5251]" name="dummyTwo_FailTest" duration-ms="3" started-at="2020-05-24T15:19:49Z" finished-at="2020-05-24T15:19:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed
at org.testng.Assert.fail(Assert.java:96)
at com.qa.testcases.DummyTestClass2.dummyTwo_FailTest(DummyTestClass2.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dummyTwo_FailTest -->
        <test-method status="PASS" signature="dummyTwo_PassTest()[pri:2, instance:com.qa.testcases.DummyTestClass2@56de5251]" name="dummyTwo_PassTest" duration-ms="1" started-at="2020-05-24T15:19:50Z" finished-at="2020-05-24T15:19:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dummyTwo_PassTest -->
      </class> <!-- com.qa.testcases.DummyTestClass2 -->
    </test> <!-- Selenium Easy Test Site Test Cases -->
  </suite> <!-- TestNgPOM Selenium Easy Test Suite -->
</testng-results>
